defaults:
  - base
  - _self_

project: vqgan_pretrain_v2_large

# Lightning Trainer
trainer:
  accelerator: gpu
  devices: auto
  strategy: ddp_find_unused_parameters_true
  precision: bf16-mixed
  max_steps: 10_000_000
  val_check_interval: 5000

sample_rate: 44100
hop_length: 512
num_mels: 160
n_fft: 2048
win_length: 2048
segment_size: 256

# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.vqgan.MixDatast
  datasets:
    high-quality-441:
      prob: 0.5
      dataset:
        _target_: fish_speech.datasets.vqgan.VQGANDataset
        filelist: data/vocoder_data_441/vq_train_filelist.txt
        sample_rate: ${sample_rate}
        hop_length: ${hop_length}
        slice_frames: ${segment_size}
    
    common-voice:
      prob: 0.5
      dataset:
        _target_: fish_speech.datasets.vqgan.VQGANDataset
        filelist: data/cv-corpus-16.0-2023-12-06/vq_train_filelist.txt
        sample_rate: ${sample_rate}
        hop_length: ${hop_length}
        slice_frames: ${segment_size}

val_dataset:
  _target_: fish_speech.datasets.vqgan.VQGANDataset
  filelist: data/vocoder_data_441/vq_val_filelist.txt
  sample_rate: ${sample_rate}
  hop_length: ${hop_length}

data:
  _target_: fish_speech.datasets.vqgan.VQGANDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 4
  batch_size: 32
  val_batch_size: 4

# Model Configuration
model:
  _target_: fish_speech.models.vqgan.VQGAN
  sample_rate: ${sample_rate}
  hop_length: ${hop_length}

  encoder:
    _target_: fish_speech.models.vqgan.modules.modules.WaveNet
    hidden_channels: 384
    kernel_size: 3
    dilation_rate: 2
    n_layers: 20
    in_channels: ${num_mels}

  vq:
    _target_: fish_speech.models.vqgan.modules.encoders.VQEncoder
    in_channels: 384
    vq_channels: 384
    codebook_size: 256
    codebook_groups: 2
    codebook_layers: 2
    downsample: 4

  decoder:
    _target_: fish_speech.models.vqgan.modules.modules.WaveNet
    hidden_channels: 384
    kernel_size: 3
    dilation_rate: 2
    n_layers: 20
    out_channels: ${num_mels}

  generator:
    _target_: fish_speech.models.vqgan.modules.decoder_v2.HiFiGANGenerator
    hop_length: ${hop_length}
    upsample_rates: [8, 8, 2, 2, 2]  # aka. strides
    upsample_kernel_sizes: [16, 16, 4, 4, 4]
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    num_mels: ${num_mels}
    upsample_initial_channel: 512
    use_template: true
    pre_conv_kernel_size: 7
    post_conv_kernel_size: 7
    ckpt_path: checkpoints/hifi-gan-base-002000000.ckpt

  discriminator:
    _target_: fish_speech.models.vqgan.modules.modules.WaveNet
    hidden_channels: 256
    kernel_size: 3
    dilation_rate: 2
    n_layers: 6
    in_channels: ${num_mels}

  mel_transform:
    _target_: fish_speech.models.vqgan.spectrogram.LogMelSpectrogram
    sample_rate: ${sample_rate}
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    win_length: ${win_length}
    n_mels: ${num_mels}

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 2e-4
    betas: [0.8, 0.99]
    eps: 1e-5

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    _partial_: true
    gamma: 0.999999  # Estimated base on LibriTTS dataset

callbacks:
  grad_norm_monitor:
    sub_module: 
      - encoder
      - vq
      - decoder
      - discriminator
